### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by tholu** [mauricerkelly/hubot-lunch#7]
```
[Tue Dec 20 2016 15:41:51 GMT+0100 (CET)] ERROR Unable to load /Users/xxx/Documents/hubot-lunch/node_modules/hubot/src/scripts/auth: Error: Cannot find module '/Users/xxx/Documents/hubot-lunch/node_modules/hubot/src/scripts/auth'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Robot.loadFile (/Users/xxx/Documents/hubot-lunch/node_modules/hubot/src/robot.coffee:230:20)
    at MockAdapter.<anonymous> (/Users/xxx/Documents/hubot-lunch/spec/lunch-spec.coffee:36:20)
    at emitNone (events.js:86:13)
    at MockAdapter.emit (events.js:185:7)
    at MockAdapter.self.run (/Users/xxx/Documents/hubot-lunch/node_modules/hubot-mock-adapter/index.js:44:14)
    at Robot.run (/Users/xxx/Documents/hubot-lunch/node_modules/hubot/src/robot.coffee:480:27)
    at Context.<anonymous> (/Users/xxx/Documents/hubot-lunch/spec/lunch-spec.coffee:40:25)
    at Hook.Runnable.run (/Users/xxx/Documents/hubot-lunch/node_modules/mocha/lib/runnable.js:196:15)
    at next (/Users/xxx/Documents/hubot-lunch/node_modules/mocha/lib/runner.js:259:10)
    at Immediate.<anonymous> (/Users/xxx/Documents/hubot-lunch/node_modules/mocha/lib/runner.js:276:5)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

It cannot find the requested `auth.coffee` in the `lunch-spec.coffee` line:

`@robot.loadFile path.resolve(path.join("node_modules/hubot/src/scripts")), "auth.coffee"`

Are you planning to fix this so it works with newer versions of hubot?

**Comment by mauricerkelly** [comment]
I probably won't get around to fixing this any time soon (I don't use this plugin these days), but I'll take a look and see if I can do anything quickly. I'm very open to contributions if you have any thoughts?

**Comment by tholu** [comment]
I ended up forking another repository (https://github.com/cagedata/hubot-lunch), so I don't think I'll find the time for fixing this, sorry. Thanks for taking a look!
